name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install lerna
        run: yarn global add lerna

      - name: Install deps and build (with cache)
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent

      - name: Setup lerna
        run: yarn setup

      - name: Lint Projects
        run: yarn lint

      - name: Test Projects
        run: yarn test
