name: Packages

on:
  push:
    paths:
      - packages/**
      - config/**
      - .github/workflows/packages.yml
      - scripts/workspace/release.sh
      - package.json
      - commitlint.config.js

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          # pulls all commits (needed for lerna / semantic release to correctly version)
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: pnpm i --frozen-lock --filter {packages/}

      - name: Lint Projects
        run: pnpm run lint --filter {packages/}

      - name: Test Projects
        run: pnpm run test --filter {packages/}

      - name: Build Projects
        run: pnpm run build --filter {packages/}

      # TODO: check this workflow with changeset + pnpm suggestions
      - name: Release Packages
        run: |
          git config --global user.name "Raul Melo"
          git config --global user.email "melo.raulf@gmail.com"
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ./.npmrc
          git reset --hard
          yarn release
        if: github.ref == 'refs/heads/main'
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
