name: size

on:
  pull_request:
    paths:
      - 'packages/**'

jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: andresz1/size-limit-action@v1
        with:
          build_script: yarn build --scope='{@raulfdm/blog-components}'
          github_token: ${{ secrets.GITHUB_TOKEN }}
