name: Renovate
on:
  workflow_dispatch:
    secrets:
      RENOVATE_TOKEN:
        required: true
    inputs:
      logLevel:
        description: 'Reason'
        required: false
        default: 'Checking for updates'
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0 0 * * *' # At 00:00 /> https://crontab.guru/#0_0_*_*_*

jobs:
  renovate:
    environment: Raul Melo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install renovate
        run: npm install -g renovate

      - name: Running Renovate
        run: renovate
        env:
          RENOVATE_CONFIG_FILE: renovate-config.js
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
