name: Website

on:
  push:
    paths:
      - 'apps/website/**'
      - 'scripts/**'
      - 'config/**'
      - '.github/workflows/website.yml'
      - .eslintignore
      - .eslintrc.js
      - package.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install lerna
        run: npm install -g pnpm

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Lint Projects
        run: pnpm run lint --filter website

      - name: Test Projects
        run: pnpm run test --filter website
